<template><div><h1 id="安装" tabindex="-1"><a class="header-anchor" href="#安装" aria-hidden="true">#</a> 安装</h1>
<div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code>brew <span class="token function">install</span> etcd
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h1 id="启动" tabindex="-1"><a class="header-anchor" href="#启动" aria-hidden="true">#</a> 启动</h1>
<p>启动</p>
<div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code>jisongyang@SongyangJi-MacBookAir ~ % brew services start etcd
<span class="token operator">==</span><span class="token operator">></span> Successfully started <span class="token variable"><span class="token variable">`</span>etcd<span class="token variable">`</span></span> <span class="token punctuation">(</span>label: homebrew.mxcl.etcd<span class="token punctuation">)</span>
jisongyang@SongyangJi-MacBookAir ~ % brew services list
Name              Status  User       File
activemq          none
etcd              started jisongyang ~/Library/LaunchAgents/homebrew.mxcl.etcd.plist
hbase             none
jenkins           none
mongodb-community none
nginx             none
rabbitmq          none
redis             none
jisongyang@SongyangJi-MacBookAir ~ % etcdctl endpoint health
<span class="token number">127.0</span>.0.1:2379 is healthy: successfully committed proposal: took <span class="token operator">=</span> <span class="token number">2</span>.418875ms
jisongyang@SongyangJi-MacBookAir ~ % etcd ctl put <span class="token string">"name"</span> <span class="token string">"bob"</span>
<span class="token punctuation">{</span><span class="token string">"level"</span><span class="token builtin class-name">:</span><span class="token string">"info"</span>,<span class="token string">"ts"</span><span class="token builtin class-name">:</span><span class="token string">"2022-12-09T03:06:16.834+0800"</span>,<span class="token string">"caller"</span><span class="token builtin class-name">:</span><span class="token string">"etcdmain/etcd.go:73"</span>,<span class="token string">"msg"</span><span class="token builtin class-name">:</span><span class="token string">"Running: "</span>,<span class="token string">"args"</span>:<span class="token punctuation">[</span><span class="token string">"etcd"</span>,<span class="token string">"ctl"</span>,<span class="token string">"put"</span>,<span class="token string">"name"</span>,<span class="token string">"bob"</span><span class="token punctuation">]</span><span class="token punctuation">}</span>
<span class="token punctuation">{</span><span class="token string">"level"</span><span class="token builtin class-name">:</span><span class="token string">"warn"</span>,<span class="token string">"ts"</span><span class="token builtin class-name">:</span><span class="token string">"2022-12-09T03:06:16.834+0800"</span>,<span class="token string">"caller"</span><span class="token builtin class-name">:</span><span class="token string">"etcdmain/etcd.go:75"</span>,<span class="token string">"msg"</span><span class="token builtin class-name">:</span><span class="token string">"failed to verify flags"</span>,<span class="token string">"error"</span><span class="token builtin class-name">:</span><span class="token string">"'ctl' is not a valid flag"</span><span class="token punctuation">}</span>
jisongyang@SongyangJi-MacBookAir ~ %
jisongyang@SongyangJi-MacBookAir ~ % etcd ctl get <span class="token string">"name"</span>
<span class="token punctuation">{</span><span class="token string">"level"</span><span class="token builtin class-name">:</span><span class="token string">"info"</span>,<span class="token string">"ts"</span><span class="token builtin class-name">:</span><span class="token string">"2022-12-09T03:06:26.364+0800"</span>,<span class="token string">"caller"</span><span class="token builtin class-name">:</span><span class="token string">"etcdmain/etcd.go:73"</span>,<span class="token string">"msg"</span><span class="token builtin class-name">:</span><span class="token string">"Running: "</span>,<span class="token string">"args"</span>:<span class="token punctuation">[</span><span class="token string">"etcd"</span>,<span class="token string">"ctl"</span>,<span class="token string">"get"</span>,<span class="token string">"name"</span><span class="token punctuation">]</span><span class="token punctuation">}</span>
<span class="token punctuation">{</span><span class="token string">"level"</span><span class="token builtin class-name">:</span><span class="token string">"warn"</span>,<span class="token string">"ts"</span><span class="token builtin class-name">:</span><span class="token string">"2022-12-09T03:06:26.364+0800"</span>,<span class="token string">"caller"</span><span class="token builtin class-name">:</span><span class="token string">"etcdmain/etcd.go:75"</span>,<span class="token string">"msg"</span><span class="token builtin class-name">:</span><span class="token string">"failed to verify flags"</span>,<span class="token string">"error"</span><span class="token builtin class-name">:</span><span class="token string">"'ctl' is not a valid flag"</span><span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>检查是否启动成功:</p>
<div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code>etcdctl endpoint health
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h1 id="安装etcd-webui" tabindex="-1"><a class="header-anchor" href="#安装etcd-webui" aria-hidden="true">#</a> 安装etcd-webui</h1>
<div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code>$ <span class="token function">git</span> clone https://github.com/henszey/etcd-browser.git
$ <span class="token builtin class-name">cd</span> etcd-browser/
$ <span class="token function">vim</span> server.js  
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>修改如下内容</p>
<div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code>var etcdHost <span class="token operator">=</span> process.env.ETCD_HOST <span class="token operator">||</span> <span class="token string">'127.0.0.1'</span><span class="token punctuation">;</span> // <span class="token operator">||</span> <span class="token string">'172.17.42.1'</span><span class="token punctuation">;</span>
var etcdPort <span class="token operator">=</span> process.env.ETCD_PORT <span class="token operator">||</span> <span class="token number">2379</span><span class="token punctuation">;</span> // <span class="token number">4001</span>
var serverPort <span class="token operator">=</span> process.env.SERVER_PORT <span class="token operator">||</span> <span class="token number">8000</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code>jisongyang@SongyangJi-MacBookAir etcd-browser % <span class="token function">node</span> server.js
proxy /api requests to etcd on <span class="token number">127.0</span>.0.1:2379
etc-browser listening on port <span class="token number">8000</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>访问：http://127.0.0.1:8000/</p>
</div></template>


